// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.codenotfound.rpc;

public interface GreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.codenotfound.rpc.Greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
